### ISSUE TITLE
Can we compare only 5 methods at a given time?

### ISSUE THREAD

**Issue by niniack** [ml-research/CLEVA-Compass#1]

**Comment by MrtnMndt** [comment]
Hey @niniack 
thanks a lot for the question & the interest! 

You are naturally _not limited to compare exactly 5 methods at a given time_. As hopefully illustrated in our readme file, the CLEVA-Compass will scale automatically depending on the amount of methods you add.

Feel free to use it at your convenience and add a flexible amount of methods. 

That said, there _presently is a limit to the amount of colors provided as a choice for methods_. This limit exists for two reasons: 

1.  Implementing a color picker in the GUI is not straightforward, because the CLEVA-Compass is rendered to LaTeX and the color needs to exist there. 

2. We believe that after a certain amount of methods are displayed, the compass will become unreadable, defeating its main purpose. We would encourage prospective users to not put "too much" into a single compass diagram. In particular, please note that the choice of illustration of a radar/star plot at the center, actually makes it easy to compare methods even if you were to plot two CLEVA-Compasses side by side! 

With the above in mind, we have just pushed a commit nevertheless to add more color options to the GUI (but not open ended, due to LaTeX limitations, let us know if you have an idea of how to implement a full color picker in LaTeX). Feel free to use those to display an overall larger amount of methods, or simply because our predefined colors weren't to your liking.  

All of the above is for the GUI version. For the python/LaTeX version of the CLEVA-Compass you can just re-define or add colors however you please in the code. It's more or less just adding a string + LaTeX color to the existing lists. 

Hope this helps, let us know if there are any remaining questions or if we can close the issue for now.

**Comment by niniack** [comment]
Hi @MrtnMndt 

Thanks a lot of for this detailed response!

For clarity, I should have asked if the limit was 5 for the provided implementation, but you got what I was going for! Yes, the limitation in the provided software makes sense from the latex color options perspective. I also understand the cluttering concern. 

Thanks for pushing the commit updating the color options. If any suggestions come to mind, I'll be sure to reach out! 

Cool tool and paper, I'm glad this repo is available!
